apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap
  labels:
    name: configmap
data:
  spring.datasource.url: "jdbc:postgresql://fiapeatsdb.cjyemig865vi.us-east-1.rds.amazonaws.com:5432/fiapeatsdb"