apiVersion: v1
kind: Secret
metadata:
  name: fiapeats-secret
type: Opaque
data:
  spring.datasource.username: c2E=  # 'sa' codificado em Base64
  spring.datasource.password: ZmlhcGVhdHMtcGFzcw==  # 'fiapeats-pass' codificado em Base64